{"trial_id": "0009", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 2, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "feature_maps", "default": 64, "conditions": [], "values": [64, 96, 128, 160, 192, 224, 256], "ordered": true}}, {"class_name": "Choice", "config": {"name": "kernel_size", "default": 3, "conditions": [], "values": [3, 5, 7, 9, 11], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dropout", "default": 0.1, "conditions": [], "values": [0.1, 0.2, 0.3, 0.4, 0.5], "ordered": true}}], "values": {"num_layers": 6, "feature_maps": 160, "kernel_size": 3, "dropout": 0.5, "tuner/epochs": 3, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 430, in _build_hypermodel\n    model = super()._build_hypermodel(hp)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\Nikla.RECHENMASCHINE\\AppData\\Local\\Temp\\ipykernel_17724\\2582181469.py\", line 13, in model_builder\n    model.add(Conv1D(filters, kernel, activation='relu'))\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras\\src\\models\\sequential.py\", line 122, in add\n    self._maybe_rebuild()\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras\\src\\models\\sequential.py\", line 149, in _maybe_rebuild\n    self.build(input_shape)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras\\src\\layers\\layer.py\", line 232, in build_wrapper\n    original_build_method(*args, **kwargs)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras\\src\\models\\sequential.py\", line 195, in build\n    x = layer(x)\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\Nikla.RECHENMASCHINE\\anaconda3\\envs\\tfenv\\lib\\site-packages\\keras\\src\\ops\\operation_utils.py\", line 221, in compute_conv_output_shape\n    raise ValueError(\nValueError: Computed output size would be negative. Received `inputs shape=(None, 1, 160)`, `kernel shape=(3, 160, 160)`, `dilation_rate=[1]`.\n"}